ARG AIRFLOW_VERSION

FROM apache/airflow:${AIRFLOW_VERSION}
ARG PLUGIN_VERSION
ARG AIRFLOW_UID

USER root
# Install git
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         git \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Do black magic tricks
RUN sed -i "s/:50000:/:${AIRFLOW_UID}:/g" /etc/passwd
USER airflow

# Install Airflow
COPY requirements-optional.txt .
RUN pip install pytest --no-cache-dir airflow-code-editor==${PLUGIN_VERSION} -r requirements-optional.txt pss && rm requirements-optional.txt
# Init airflow db
RUN airflow db init
# Create user 'admin' with password 'admin'
RUN airflow users create -r Admin -u admin -e admin@example.com -f admin -l admin -p admin
RUN airflow sync-perm
# Git config
RUN git config --global --add safe.directory /opt/airflow/dags
RUN git config --global user.email "dev@example.com"
RUN git config --global user.name "Test"

ENV PYTHONPATH = /home/airflow
