ARG AIRFLOW_VERSION=invalid_default

FROM apache/airflow:${AIRFLOW_VERSION}
ARG PLUGIN_VERSION=invalid_default

USER root
# Install git and vim
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         git \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow

# Install Airflow
COPY requirements-optional.txt .
RUN pip install \
    pytest \
    coverage[toml] \
    pytest-cov \
    --no-cache-dir airflow-code-editor==${PLUGIN_VERSION} -r requirements-optional.txt pss && rm requirements-optional.txt
# Init airflow db
RUN airflow db migrate
# Set base_url
# RUN sed -i 's/# base_url =.*/base_url = http:\/\/localhost:8080\/airflow/' /opt/airflow/airflow.cfg
# Configure GIT
RUN git config --global --add safe.directory /opt/airflow/dags
RUN git config --global user.email "dev@example.com"
RUN git config --global user.name "Test"

ENV PYTHONPATH=/home/airflow
